Save.

diff --git a/bin/setup-software b/bin/setup-software
--- a/bin/setup-software
+++ b/bin/setup-software
@@ -263,28 +263,14 @@
         return "${?}"
     }
 
-    function UpdateOrCloneGitRepo
+    function UpdateGitRepo
     {
-        local DO_AUTO_ANSWER_YES=false
-
-        if [[ "${4}" == true ]]; then
-            DO_AUTO_ANSWER_YES=true
-        fi
-
-        if [[ -z "${3}" ]] \
-            || [[ -z "${2}" ]] \
-            || [[ -z "${1}" ]]; then
-            echo -e "${_PREFIX_ERROR} Input values are empty."
-            return 1
-        fi
-
         if [[ ! -d "${1}${2}" ]] \
             && ! sudo mkdir -p "${1}${3}"; then
             echo -e "${_PREFIX_ERROR} Failed to create directory '${1}${3}'."
             return 1
         fi
 
-        # <remarks> Update existing GitHub repository. </remarks>
         if [[ -d "${1}${2}" ]]; then
             cd "${1}${2}"
 
@@ -295,35 +281,11 @@
 
             return 0
 
-        # <remarks> Clone new GitHub repository. </remarks>
         elif [[ -d "${1}${3}" ]]; then
-            for COUNT in "${_COUNT_LIST[@]}"; do
-                if ! "${DO_AUTO_ANSWER_YES}"; then
-                    read -r -p "Clone repo '${2}'? [Y/n]: " ANSWER
-                else
-                    ANSWER="Y"
-                fi
-
-                case "${ANSWER}" in
-                    [Yy]* )
-                        cd "${1}${3}"
-
-                        if ! git clone "https://github.com/${2}" &> /dev/null; then
-                            echo -e "${_PREFIX_ERROR} Failed to download repository."
-                            return 1
-                        fi
-
-                        return 0 ;;
-
-                    [Nn]* )
-                        return 255 ;;
-
-                    * )
-                        echo "Please answer 'Y' or 'N'." ;;
-                esac
-            done
-
-            return 1
+            if ! git clone "https://github.com/${2}" &> /dev/null; then
+                echo -e "${_PREFIX_ERROR} Failed to clone repository."
+                return 1
+            fi
 
         else
             return 1
