Save.

diff --git a/bin/setup-software b/bin/setup-software
--- a/bin/setup-software
+++ b/bin/setup-software
@@ -14,63 +14,52 @@
 # <functions>
     function SetParameters
     {
-        if [[ ! -z "${_ARE_COMMON_PARAMS_SET}" ]] \
+        if [[ ! -z "${_ARE_PARAMS_SET_SETUP_SOFTWARE}" ]] \
             && "${_ARE_COMMON_PARAMS_SET}"; then
             return 0
         fi
 
-        declare -g _ARE_COMMON_PARAMS_SET=true
+        declare -g _ARE_PARAMS_SET_SETUP_SOFTWARE=true
 
-        # <remarks> Execution Flags </remarks>
-        declare -g _IS_EXECUTION_QUIET=false
-
-        # <remarks>
-        # Color coding
-        # Reference URL: 'https://www.shellhacks.com/bash-colors'
-        # </remarks>
-        declare -g _SET_COLOR_GREEN='\033[0;32m'
-        declare -g _SET_COLOR_RED='\033[0;31m'
-        declare -g _SET_COLOR_YELLOW='\033[0;33m'
-        declare -g _RESET_COLOR='\033[0m'
-
-        # <remarks> Append output </remarks>
-        declare -g _PREFIX_NOTE="${_SET_COLOR_YELLOW}Note:${_RESET_COLOR}"
-        declare -g _PREFIX_ERROR="${_SET_COLOR_YELLOW}An error occurred:${_RESET_COLOR}"
-        declare -g _PREFIX_FAIL="${_SET_COLOR_RED}Failure:${_RESET_COLOR}"
-        declare -g _PREFIX_PASS="${_SET_COLOR_GREEN}Success:${_RESET_COLOR}"
-        declare -g _SUFFIX_FAIL="${_SET_COLOR_RED}[Failure]${_RESET_COLOR}"
-        declare -g _SUFFIX_PASS="${_SET_COLOR_GREEN}[Success]${_RESET_COLOR}"
-        declare -g _SUFFIX_SKIP="${_SET_COLOR_YELLOW}[Skipped]${_RESET_COLOR}"
-        declare -g _SUFFIX_WORK="${_SET_COLOR_YELLOW}[Working]${_RESET_COLOR}"
-
-        # <remarks> File templates. </remarks>
-        declare -g _PREFIX_COMMENT="#"              # <note> Added this var, to prevent IDE from showing visual errors when a string contains a comment variable. </note>
-
-        declare -ga _DISCLAIMER_FILE_CONTENTS=(
-            "${_PREFIX_COMMENT} Generated by 'portellam/deploy-vfio-main'"
-            "${_PREFIX_COMMENT} WARNING: Any modifications to this file will be modified by 'deploy-vfio-main'"
-            "${_PREFIX_COMMENT}"
-        )
-
-        declare -ga _VFIO_DISCLAIMER_FILE_CONTENTS=(
-            "${_DISCLAIMER_FILE_CONTENTS[@]}"
-            "${_PREFIX_COMMENT} Run lspci to view hardware information."
-            "${_PREFIX_COMMENT} You must run update-initramfs(8) to effect this change."
-            "${_PREFIX_COMMENT}"
-        )
-
-        # <remarks> Memory </remarks>
-        declare -gi _1_GIB_IN_KIB=1048576
-        declare -gi _2_MIB_IN_KIB=2048
-        declare -gi _AVAILABLE_MEMORY=0
-        declare -gi _MAX_MEMORY=$( cat /proc/meminfo | grep MemTotal | cut -d ":" -f 2 | awk 'END {print $1}' )
-        declare -gi _MIN_MEMORY=$(( 8 * ${_1_GIB_IN_KIB} ))
-        SetFreeMemory
+        declare -gr _LIST_OF_OPERATING_SYSTEMS_WITH_APT_DELIM="debian bodhi deepin knoppix mint peppermint pop ubuntu kubuntu lubuntu xubuntu"
+        declare -gr _LIST_OF_OPERATING_SYSTEMS_WITH_DNF_OR_YUM_DELIM="redhat alma berry centos cern clearos elastix fedora fermi frameos mageia opensuse oracle scientific suse"
+        declare -gr _LIST_OF_OPERATING_SYSTEMS_WITH_PACMAN_DELIM="arch manjaro"
+        declare -gr _LIST_OF_OPERATING_SYSTEMS_WITH_PORTAGE_DELIM="gentoo"
+        declare -gr _LIST_OF_OPERATING_SYSTEMS_WITH_URPMI_DELIM="opensuse"
+        declare -gr _LIST_OF_OPERATING_SYSTEMS_WITH_ZYPPER_DELIM="mandriva mageia"
 
         # <remarks> System validation </remarks>
-        declare -g _OUTPUT_INVALID_PACKAGE_MANAGER="${_PREFIX_ERROR} Command '${_PACKAGE_MANAGER}' is not supported."
-        declare -gl _PACKAGE_MANAGER
-        declare -gl _OPERATING_SYSTEM="$( lsb_release -is )"
+        declare -gl _PACKAGE_MANAGER=""
+        GetPackageManager
+    }
+
+    function SetCommandToInstallPackage
+    {
+        case true in
+            "apt" )
+                apt list "${1}" ;;
+
+            "dnf" )
+                dnf search "${1}" ;;
+
+            "pacman" )
+                pacman -Ss "${1}" ;;
+
+            "gentoo" )
+                emerge --search "${1}" ;;
+
+            "urpmi" )
+                urpmq "${1}" ;;
+
+            "yum" )
+                yum search "${1}" ;;
+
+            "zypper" )
+                zypper se "${1}" ;;
+
+            * )
+                return 1 ;;
+        esac
     }
 
     function FindPackage
@@ -104,7 +93,6 @@
                 zypper se "${1}" ;;
 
             * )
-                echo -e "${_OUTPUT_INVALID_PACKAGE_MANAGER}"
                 return 1 ;;
         esac
 
@@ -123,6 +111,70 @@
         fi
 
         return "${_LAST_EXIT_CODE}"
+    }
+
+    # function GetLinuxDistro
+    # {
+    #     local KERNEL="$( uname -o | tr '[:upper:]' '[:lower:]' )"
+
+    #     if [[ -z "${KERNEL}" ]]; then
+    #         echo -e "${_PREFIX_ERROR} Failed to parse system kernel."
+    #         return 1
+    #     fi
+
+    #     if [[ -z "${_OPERATING_SYSTEM_DISTRIBUTION_NAME}" ]]; then
+    #         echo -e "${_PREFIX_ERROR} Failed to parse operating system."
+    #         return 1
+    #     fi
+
+    #     if [[ "${KERNEL}" != *"linux"* ]]; then
+    #         echo -e "${_PREFIX_ERROR} Kernel '$( uname -o )' is not supported."
+    #         return 1
+    #     fi
+
+    #     if ! GetPackageManager; then
+    #         echo -e "${_PREFIX_ERROR} Distribution '$( lsb_release -is )' is not supported."
+    #         return 1
+    #     fi
+
+    #     return 0
+    # }
+
+    function GetPackageManager
+    {
+        if [[ "${_LIST_OF_OPERATING_SYSTEMS_WITH_APT_DELIM}" =~ .*${_OPERATING_SYSTEM_DISTRIBUTION_NAME}.* ]]; then
+            _PACKAGE_MANAGER="apt"
+
+        elif [[ "${_LIST_OF_OPERATING_SYSTEMS_WITH_DNF_OR_YUM_DELIM}" =~ .*${_OPERATING_SYSTEM_DISTRIBUTION_NAME}.* ]]; then
+            _PACKAGE_MANAGER="dnf"
+
+            if command -v "${_PACKAGE_MANAGER}"; then
+                return 0
+            fi
+
+            _PACKAGE_MANAGER="yum"
+
+        elif [[ "${_LIST_OF_OPERATING_SYSTEMS_WITH_PACMAN_DELIM}" =~ .*${_OPERATING_SYSTEM_DISTRIBUTION_NAME}.* ]]; then
+            _PACKAGE_MANAGER="pacman"
+
+        elif [[ "${_LIST_OF_OPERATING_SYSTEMS_WITH_PORTAGE_DELIM}" =~ .*${_OPERATING_SYSTEM_DISTRIBUTION_NAME}.* ]]; then
+            _PACKAGE_MANAGER="portage"
+
+        elif [[ "${_LIST_OF_OPERATING_SYSTEMS_WITH_URPMI_DELIM}" =~ .*${_OPERATING_SYSTEM_DISTRIBUTION_NAME}.* ]]; then
+            _PACKAGE_MANAGER="urpmi"
+
+        elif [[ "${_LIST_OF_OPERATING_SYSTEMS_WITH_ZYPPER_DELIM}" =~ .*${_OPERATING_SYSTEM_DISTRIBUTION_NAME}.* ]]; then
+            _PACKAGE_MANAGER="zypper"
+
+        else
+            _PACKAGE_MANAGER=""
+        fi
+
+        if ! command -v "${_PACKAGE_MANAGER}" &> /dev/null; then
+            return 1
+        fi
+
+        return 0
     }
 
     function InstallPackage
@@ -168,7 +220,6 @@
                 zypper refresh && zypper in "${1}" ;;
 
             * )
-                echo -e "${_OUTPUT_INVALID_PACKAGE_MANAGER}"
                 false ;;
         esac
 
@@ -192,7 +243,6 @@
                 GET_COMMAND="sudo dpkg -s" ;;
 
             * )
-                echo -e "${_OUTPUT_INVALID_PACKAGE_MANAGER}"
                 return 1 ;;
         esac
 
@@ -240,7 +290,6 @@
                 zypper remove "${1}" ;;
 
             * )
-                echo -e "${_OUTPUT_INVALID_PACKAGE_MANAGER}"
                 false ;;
         esac
 
