Update setup-apt

diff --git a/bin/setup-apt b/bin/setup-apt
--- a/bin/setup-apt
+++ b/bin/setup-apt
@@ -1,88 +1,194 @@
 #!/bin/false
 
-declare -ga _COUNT_LIST=$( seq 0 2 )
-declare -g _OPERATING_SYSTEM_DISTRIBUTION_NAME=$( lsb_release -i | awk 'END {print $2}' )
-declare -gi _OPERATING_SYSTEM_RELEASE_NAME=$( lsb_release -c | awk 'END {print $2}' )
-declare -g _OPERATING_SYSTEM_RELEASE_NUMBER=$( lsb_release -r | awk 'END {print $2}' )
-declare -g _SOURCES_FILE_NAME="/etc/apt/sources.list"
+# <params>
+    declare -a _COUNT_LIST=$( seq 0 2 )
+    _OPERATING_SYSTEM_DISTRIBUTION_NAME=$( lsb_release -i | awk 'END {print $2}' )
+    _OPERATING_SYSTEM_PREFERRED_RELEASE_NAME=""
+    _OPERATING_SYSTEM_RELEASE_NAME=$( lsb_release -c | awk 'END {print $2}' )
+    _OPERATING_SYSTEM_RELEASE_NUMBER=$( lsb_release -r | awk 'END {print $2}' )
+    _SOURCES_FILE_NAME="/etc/apt/sources.list"
 
-declare -gi _DEBIAN_LATEST_RELEASE_NUMBER=12
-declare -g _DEBIAN_LATEST_RELEASE_NAME="bookworm"
+    _SYSTEM_IS_ARCH=false
+    _SYSTEM_IS_DEBIAN=false
+    _SYSTEM_IS_FEDORA=false
+    _SYSTEM_IS_REDHAT=false
+    _SYSTEM_IS_UBUNTU=false
 
-function GetPromptsFromAnswerList
-{
-    local -n ANSWER_LIST_REFERENCE="${1}"
-    local -n PROMPT_REFERENCE="${2}"
-    local -n WARNING_REFERENCE="${3}"
-    PROMPT_REFERENCE=""
-    WARNING_REFERENCE=""
-    local -i LIST_MAX_INDEX=$( head -n 1 <<< $( sort -r <<< "${!ANSWER_LIST_REFERENCE[*]}" ) )
-
-    for KEY in "${!ANSWER_LIST_REFERENCE[@]}"; do
-        local ANSWER="${ANSWER_LIST_REFERENCE[$KEY]}"
-        local FORMATTED_ANSWER="("$( echo ${ANSWER::1} | tr '[:lower:]' '[:upper:]' )")${ANSWER:1}"
-        local FORMATTED_WARNING="'"$( echo ${ANSWER::1} | tr '[:lower:]' '[:upper:]' )'"'
-
-        if [[ "${KEY}" -lt "${#LIST_MAX_INDEX[@]}" ]]; then
-            ROMPT_REFERENCE+="${FORMATTED_ANSWER}/"
-            WARNING_REFERENCE+="${FORMATTED_WARNING}, "
-        else
-            ROMPT_REFERENCE+="${FORMATTED_ANSWER}"
-            WARNING_REFERENCE+="or ${FORMATTED_WARNING}."
-        fi
-    done
-
-    PROMPT_REFERENCE="[${PROMPT_REFERENCE}]: "
-    WARNING_REFERENCE="Please answer ${WARNING_REFERENCE}."
-    return 0
-}
-
-function GetReleaseBranchFromPrompt
-{
-    local -n REFERENCE="${1}"
-    local PROMPT=""
-    local -al ANSWER_LIST=(
+    # <summary> Debian </summary>
+    _DEBIAN_LATEST_RELEASE_NAME="bookworm"
+    declare -al _DEBIAN_RELEASE_BRANCH_LIST=(
         "stable"
         "testing"
         "unstable"
     )
+# </params>
 
-    GetPromptFromAnswerList "ANSWER_LIST" "PROMPT"
+# <functions>
+    function DoesSourcesFileExist
+    {
+        if ! find "${_SOURCES_FILE_NAME}" &> /dev/null; then
+            echo -e "Failed to find package sources file."
+            return 1
+        fi
 
-    for COUNT in "${_COUNT_LIST[@]}"; do
-        local -l ANSWER
-        echo -e "Select ${_OPERATING_SYSTEM_DISTRIBUTION_NAME} release branch."
-        read -r -p "${PROMPT}" ANSWER
+        return 0
+    }
 
-        for THE_ANSWER in "${ANSWER_LIST[@]}"; do
-            if [[ "${THE_ANSWER}" == "${ANSWER}" ]]; then
-                REFERENCE="${ANSWER}"
-                return 0
+    function GetLinuxDistribution
+    {
+        case "${_OPERATING_SYSTEM_DISTRIBUTION_NAME}" in
+            "arch" )
+                _SYSTEM_IS_ARCH=true ;;
+
+            "debian" )
+                _SYSTEM_IS_DEBIAN=true ;;
+
+            "fedora" )
+                _SYSTEM_IS_FEDORA=true ;;
+
+            "redhat" )
+                _SYSTEM_IS_REDHAT=true ;;
+
+            "ubuntu" )
+                _SYSTEM_IS_UBUNTU=true ;;
+
+            * )
+                echo -e "Operating system is not recognized."
+                return 1 ;;
+        esac
+
+        return 0
+    }
+
+    function GetPromptsFromAnswerList
+    {
+        local -n ANSWER_LIST_REFERENCE="${1}"
+        local -n PROMPT_REFERENCE="${2}"
+        local -n WARNING_REFERENCE="${3}"
+        PROMPT_REFERENCE=""
+        WARNING_REFERENCE=""
+        local -i LIST_MAX_INDEX=$( head -n 1 <<< $( sort -r <<< "${!ANSWER_LIST_REFERENCE[*]}" ) )
+
+        for KEY in "${!ANSWER_LIST_REFERENCE[@]}"; do
+            local ANSWER="${ANSWER_LIST_REFERENCE[$KEY]}"
+            local FORMATTED_ANSWER="("$( echo ${ANSWER::1} | tr '[:lower:]' '[:upper:]' )")${ANSWER:1}"
+            local FORMATTED_WARNING="'"$( echo ${ANSWER::1} | tr '[:lower:]' '[:upper:]' )'"'
+
+            if [[ "${KEY}" -lt "${#LIST_MAX_INDEX[@]}" ]]; then
+                ROMPT_REFERENCE+="${FORMATTED_ANSWER}/"
+                WARNING_REFERENCE+="${FORMATTED_WARNING}, "
+            else
+                ROMPT_REFERENCE+="${FORMATTED_ANSWER}"
+                WARNING_REFERENCE+="or ${FORMATTED_WARNING}."
             fi
         done
 
-        echo "Please answer 'S', 'T', 'U'."
-    done
+        PROMPT_REFERENCE="[${PROMPT_REFERENCE}]: "
+        WARNING_REFERENCE="Please answer ${WARNING_REFERENCE}."
+        return 0
+    }
 
-    return 1
-}
+    function GetReleaseBranchFromPrompt
+    {
+        local -n REFERENCE="${1}"
+        local PROMPT WARNING
+        SetReleaseBranch "ANSWER_LIST" || return 1
+        GetPromptFromAnswerList "ANSWER_LIST" "PROMPT" "WARNING"
 
-# function PromptToChangeSourcesFile
-# {
-#     case 
-# }
+        for COUNT in "${_COUNT_LIST[@]}"; do
+            local -l ANSWER
+            echo -e "Select ${_OPERATING_SYSTEM_DISTRIBUTION_NAME} release branch."
+            read -r -p "${PROMPT}" ANSWER
 
-function DoesSourcesFileExist
-{
-    if ! find "${_SOURCES_FILE_NAME}"; then
-        echo -e "Failed to find package sources file."
+            for THE_ANSWER in "${ANSWER_LIST[@]}"; do
+                if [[ "${THE_ANSWER}" == "${ANSWER}" ]]; then
+                    REFERENCE="${ANSWER}"
+                    return 0
+                fi
+            done
+
+            echo -e "${WARNING}"
+        done
+
         return 1
-    fi
+    }
 
-    return 0
-}
+    function PromptToChangeSourcesFile
+    {
+        local -al ANSWER_LIST=(
+            "branch"
+            "version"
+            "none"
+        )
 
-function UpdateSourcesFile
-{
-    sed -i "s/cbullseye/bookworm/g" /etc/apt/sources.list
-}
+        local PROMPT WARNING
+        GetPromptFromAnswerList "ANSWER_LIST" "PROMPT" "WARNING"
+
+        for COUNT in "${_COUNT_LIST[@]}"; do
+            local -l ANSWER
+            echo -e "Change ${_OPERATING_SYSTEM_DISTRIBUTION_NAME} sources file?"
+            read -r -p "${PROMPT}" ANSWER
+
+            case "${ANSWER}" in
+                "${ANSWER_LIST[0]}" )
+                    GetReleaseBranchFromPrompt "_OPERATING_SYSTEM_PREFERRED_RELEASE_NAME"
+                    return "${?}" ;;
+
+                "${ANSWER_LIST[1]}" )
+                    SetReleaseVersion "_OPERATING_SYSTEM_PREFERRED_RELEASE_NAME"
+                    return "${?}" ;;
+            esac
+
+            echo -e "${WARNING}"
+        done
+
+        UpdateSourcesFile
+        return 0
+    }
+
+    function SetReleaseBranch
+    {
+        local -n REFERENCE="${1}"
+
+        case true in
+            "${_SYSTEM_IS_DEBIAN}" )
+                REFERENCE="${_DEBIAN_RELEASE_BRANCH_LIST[@]}" ;;
+
+            * )
+                echo -e "Operating system is not supported."
+                return 1 ;;
+        esac
+
+        return 0
+    }
+
+    function SetReleaseVersion
+    {
+        local -n REFERENCE="${1}"
+
+        case true in
+            "${_SYSTEM_IS_DEBIAN}" )
+                REFERENCE="${_DEBIAN_LATEST_RELEASE_NUMBER}" ;;
+
+            * )
+                echo -e "Operating system is not supported."
+                return 1 ;;
+        esac
+
+        return 0
+    }
+
+    function UpdateSourcesFile
+    {
+        if ! DoesSourcesFileExist \
+            || ! sed -i "s/${_OPERATING_SYSTEM_RELEASE_NAME}/${_OPERATING_SYSTEM_PREFERRED_RELEASE_NAME}/g" "${_SOURCES_FILE_NAME}" &> /dev/null; then
+            echo -e "Failed to edit package sources file."
+            return 1
+        fi
+
+        return 0
+    }
+# </functions>
+
+GetLinuxDistribution
+PromptToChangeSourcesFile
